name: CI - ROS - Linux
on: push

jobs:
  ros:
    name: "ROS ${{ matrix.ROS_DISTRO }} - Prerelease: ${{ matrix.PRERELEASE }}"
    strategy:
      fail-fast: false
      matrix:
        ROS_DISTRO: [humble, jazzy, kilted, rolling]
        PRERELEASE: [true, false]
    env:
      CCACHE_DIR: ${{ github.workspace }}/.ccache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/cache@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-${{ matrix.ROS_DISTRO }}-${{github.run_id}}
          restore-keys: ccache-${{ matrix.ROS_DISTRO }}-
      - uses: ros-industrial/industrial_ci@ba2a3d0f830f8051b356711a8df2fedfc5d256cf
        env:
          CMAKE_ARGS: -DBUILD_PYTHON_INTERFACE=ON -DBUILD_TESTING=ON -DBUILD_EXAMPLES=ON -DBUILD_BENCHMARKS=ON
          PRERELEASE: ${{ matrix.PRERELEASE }}
          VERBOSE_OUTPUT: true
          VERBOSE_TESTS: true
          ROS_DISTRO: ${{ matrix.ROS_DISTRO }}
